
    <!-- ...:::: Start Breadcrumb Section:::... -->
    <div class="breadcrumb-section">
        <div class="breadcrumb-wrapper">
            <div class="container">
                <div class="row">
                    <div class="col-12 d-flex justify-content-between justify-content-md-between  align-items-center flex-md-row flex-column">
                        <h3 class="breadcrumb-title">Корзина</h3>
                        <div class="breadcrumb-nav">
                            <nav aria-label="breadcrumb">
                                <ul>
                                    <li><a href="/">Главная</a></li>
                                    <li><a href="/shop">Магазин</a></li>
                                    <li class="active" aria-current="page">Корзина</li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ...:::: End Breadcrumb Section:::... -->

  <?php if (!empty($basket)): ?>
    <!-- ...:::: Start Cart Section:::... -->
    <div class="cart-section">
        <!-- Start Cart Table -->
        <div class="cart-table-wrapper">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="table_desc" id="basket_desc">
                            <div class="table_page table-responsive">
                                <table>
                                    <!-- Start Cart Table Head -->
                                    <thead>
                                        <tr>
                                            <th class="product_remove">Удалить</th>
                                            <th class="product_thumb">Изображение</th>
                                            <th class="product_name">Название</th>
                                            <th class="product-price">Цена</th>
                                            <th class="product_quantity">Всего</th>
                                            <th class="product_total">Итого</th>
                                        </tr>
                                    </thead> <!-- End Cart Table Head -->
                                    <tbody class="basket_product_list">
                                        <form action="">
                                        <!-- Start Cart Single Item-->
                                        <?php foreach ($basket as $product): ?>
                                        <tr class="basket_row_product">
                                            <td class="product_remove"><a class="product_delete" data-id="<?php echo $product['id']; ?>"><i class="fa fa-trash-o"></i></a></td>
                                            <td class="product_thumb"><a href="/product/?id=<?php echo $product['id']; ?>"><img src="/assets/images/products_images/small/<?php echo $product['title_img']; ?>" alt="img"></a></td>
                                            <td class="product_name"><a href="/product/?id=<?php echo $product['id']; ?>"><?php echo $product['title_good']; ?></a></td>
                                            <td class="product-price" data-price="<?php echo $product['price']; ?>"><?php echo $product['price']; ?> руб.</td>
                                            <td class="product_quantity" data-quantity="<?php echo $product['quantity']; ?>"><input min="1" max="100" value="<?php echo $product['quantity']; ?>" type="number"><label>/шт.</label></td>
                                            <td class="product_total"><?php echo $product['price'] * $product['quantity']; ?> руб.</td>
                                        </tr>
                                        <?php endforeach ?>
                                        <!-- End Cart Single Item-->
                                        <!-- Start Cart Single Item-->
                                        </form>
                                    </tbody>
                                </table>
                            </div>
                            <div class="cart_submit">
                                <button type="submit" class="cart_submit_change">Обновить корзину</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div> <!-- End Cart Table -->

        <!-- Start Coupon Start -->
        <div class="coupon_area">
            <div class="container">
                <div class="row">
                    <!--<div class="col-lg-6 col-md-6">
                        <div class="coupon_code left">
                            <h3>Coupon</h3>
                            <div class="coupon_inner">
                                <p>Enter your coupon code if you have one.</p>
                                <input placeholder="Coupon code" type="text">
                                <button type="submit">Apply coupon</button>
                            </div>
                        </div>
                    </div>-->
                    <div class="col-lg-8 col-md-6">
                        <div class="coupon_code right">
                            <h3>Итого</h3>
                            <div class="coupon_inner">
                                <div class="cart_subtotal">
                                    <p>Цена</p>

                                    <p class="cart_amount basket_price"></p>
                                </div>
                                <div class="cart_subtotal ">
                                    <p>Стоимость доставки</p>
                                    <p class="cart_amount ship_price" data-ship="500"><span>стандартная ставка:</span> 500 руб.</p>
                                </div>
                                <!--<a href="#">Calculate shipping</a>-->

                                <div class="cart_subtotal">
                                    <p>Всего к оплате</p>
                                    <p class="cart_amount total_price"></p>
                                </div>
                                <div class="checkout_btn">
                                    <a href="#">Перейти к оформлению</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div> <!-- End Coupon Start -->

    </div>
    <!-- ...:::: End Cart Section:::... -->
  <?php else: ?>
    <div class="container" data-widget="emptyCart">
          <h4 class="title">Корзина пуста</h4>
          <p>Воспользуйтесь поиском, чтобы найти всё что нужно.</p>
          <br>
    </div>
  <?php endif ?>

