<!-- ...:::: Start Breadcrumb Section:::... -->
<div class="breadcrumb-section">
    <div class="breadcrumb-wrapper">
        <div class="container">
            <div class="row">
                <div class="col-12 d-flex justify-content-between justify-content-md-between  align-items-center flex-md-row flex-column">
                    <h3 class="breadcrumb-title">Product Details Variable</h3>
                    <div class="breadcrumb-nav">
                        <nav aria-label="breadcrumb">
                            <ul>
                                <li><a href="/">Home</a></li>
                                <li><a href="shop-grid-sidebar-left.html">Shop</a></li>
                                <li class="active" aria-current="page">Product Details Variable</li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> <!-- ...:::: End Breadcrumb Section:::... -->

<!-- Start Product Details Section -->
<div class="product-details-section">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="product-details-gallery-area">
                    <div class="product-large-image product-large-image-horaizontal">
                        <?php $collect = explode(',', $product['title_img']); ?>
                        <?php foreach ($collect as $img): ?>
                            <div class="product-image-large-single zoom-image-hover">
                                <img src="/assets/images/products_images/big/<?php echo $img ?>" alt="Product Image">
                            </div>
                        <?php endforeach ?>
                    </div>
                    <div class="product-image-thumb product-image-thumb-horizontal pos-relative">
                        <?php foreach ($collect as $img): ?>
                            <div class="product-image-thumb-single">
                                <img class="img-fluid" src="/assets/images/products_images/big/<?php echo $img ?>" alt="Product Image">
                            </div>
                        <?php endforeach ?>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="product-details-content-area">
                    <!-- Start  Product Details Text Area-->
                    <div class="product-details-text">
                        <h4 class="title"><?php echo $product['title_good'] ?></h4>
                        <div class="d-flex align-items-center">
                            <div class="product-review">
                                <span class="review-fill"><i class="fa fa-star"></i></span>
                                <span class="review-empty"><i class="fa fa-star"></i></span>
                                <span class="review-empty"><i class="fa fa-star"></i></span>
                                <span class="review-empty"><i class="fa fa-star"></i></span>
                                <span class="review-empty"><i class="fa fa-star"></i></span>
                            </div>
                            <a href="" class="customer-review">(оценка покупателей)</a>
                        </div>
                        <div class="price"><del><?php echo $product['price'] ?> руб.</del><?php echo $product['price'] ?> руб.</div>
                        <p><?php echo $product['description'] ?></p>
                    </div> <!-- End  Product Details Text Area-->
                    <!-- Start Product Variable Area -->
                    <div class="product-details-variable">
                        <h4 class="title">Available Options</h4>
                        <!-- Product Variable Single Item -->
                        <div class="variable-single-item">
                            <span>Color</span>
                            <div class="product-variable-color">
                                <label for="product-color-red">
                                    <input name="product-color" id="product-color-red" class="color-select" type="radio" checked>
                                    <span class="product-color-red"></span>
                                </label>
                                <label for="product-color-tomato">
                                    <input name="product-color" id="product-color-tomato" class="color-select" type="radio" checked>
                                    <span class="product-color-tomato"></span>
                                </label>
                                <label for="product-color-green">
                                    <input name="product-color" id="product-color-green" class="color-select" type="radio">
                                    <span class="product-color-green"></span>
                                </label>
                                <label for="product-color-light-green">
                                    <input name="product-color" id="product-color-light-green" class="color-select" type="radio">
                                    <span class="product-color-light-green"></span>
                                </label>
                                <label for="product-color-blue">
                                    <input name="product-color" id="product-color-blue" class="color-select" type="radio">
                                    <span class="product-color-blue"></span>
                                </label>
                                <label for="product-color-light-blue">
                                    <input name="product-color" id="product-color-light-blue" class="color-select" type="radio">
                                    <span class="product-color-light-blue"></span>
                                </label>
                            </div>
                        </div>
                        <!-- Product Variable Single Item -->
                        <div class="d-flex align-items-center">
                            <div class="variable-single-item ">
                                <span>Quantity</span>
                                <div class="product-variable-quantity">
                                    <input min="1" max="100" value="1" type="number">
                                </div>
                            </div>

                            <div class="product-add-to-cart-btn">
                                <a href="#" data-toggle="modal" data-target="#modalAddcart">В корзину</a>
                            </div>
                        </div>

                        <!-- Product Variable Single Item -->
                        <div class="variable-single-item">
                            <span>Size</span>
                            <select class="product-variable-size">
                                <option selected value="1"> size in option</option>
                                <option value="2">s</option>
                                <option value="3">m</option>
                                <option value="4">l</option>
                                <option value="5">xl</option>
                                <option value="6">xxl</option>
                            </select>
                        </div>
                    </div> <!-- End Product Variable Area -->
                    <!-- Start  Product Details Meta Area-->
                    <div class="product-details-meta mb-20">
                        <ul>
                            <li><a href=""><i class="icon-heart"></i>Add to wishlist</a></li>
                            <li><a href=""><i class="icon-repeat"></i>Compare</a></li>
                        </ul>
                    </div> <!-- End  Product Details Meta Area-->
                    <!-- Start  Product Details Social Area-->
                    <div class="product-details-social">
                        <ul>
                            <li><a href="#" class="facebook"><i class="fa fa-facebook"></i>Like</a></li>
                            <li><a href="#" class="twitter"><i class="fa fa-twitter"></i>Tweet</a></li>
                            <li><a href="#" class="pinterest"><i class="fa fa-pinterest"></i>Save</a></li>
                            <li><a href="#" class="google-plus"><i class="fa fa-google-plus"></i>Save</a></li>
                            <li><a href="#" class="linkedin"><i class="fa fa-linkedin"></i>Linked</a></li>
                        </ul>
                    </div> <!-- End  Product Details Social Area-->
                </div>
            </div>
        </div>
    </div>
</div> <!-- End Product Details Section -->

<!-- Start Product Content Tab Section -->
<div class="product-details-content-tab-section section-inner-bg section-top-gap-100">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="product-details-content-tab-wrapper">

                    <!-- Start Product Details Tab Button -->
                    <ul class="nav tablist product-details-content-tab-btn d-flex justify-content-center">
                        <li><a class="nav-link active" data-toggle="tab" href="#description">
                                <h5>Описание</h5>
                            </a></li>
                        <li><a class="nav-link" data-toggle="tab" href="#specification">
                                <h5>Спецификация</h5>
                            </a></li>
                        <li><a class="nav-link" data-toggle="tab" href="#review">
                                <h5>Отзывы (<?php echo count($reviews); ?>)</h5>
                            </a></li>
                    </ul> <!-- End Product Details Tab Button -->

                    <!-- Start Product Details Tab Content -->
                    <div class="product-details-content-tab">
                        <div class="tab-content">
                            <!-- Start Product Details Tab Content Singel -->
                            <div class="tab-pane active show" id="description">
                                <div class="single-tab-content-item">
                                    <p><?php echo $product['description'] ?></p>
                                </div>
                            </div> <!-- End Product Details Tab Content Singel -->
                            <!-- Start Product Details Tab Content Singel -->
                            <div class="tab-pane" id="specification">
                                <div class="single-tab-content-item">
                                    <table class="table table-bordered mb-20">
                                        <tbody>
                                        <tr>
                                            <th scope="row">Compositions</th>
                                            <td>Polyester</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">Styles</th>
                                            <td>Girly</td>
                                        <tr>
                                            <th scope="row">Properties</th>
                                            <td>Short Dress</td>
                                        </tr>
                                        </tbody>
                                    </table>
                                    <p>Fashion has been creating well-designed collections since 2010. The brand offers feminine designs delivering stylish separates and statement dresses which have since evolved into a full ready-to-wear collection in which every item is a vital part of a woman's wardrobe. The result? Cool, easy, chic looks with youthful elegance and unmistakable signature style. All the beautiful pieces are made in Italy and manufactured with the greatest attention. Now Fashion extends to a range of accessories including shoes, hats, belts and more!</p>
                                </div>
                            </div> <!-- End Product Details Tab Content Singel -->
                            <!-- Start Product Details Tab Content Singel -->
                            <div class="tab-pane" id="review">
                                <div class="single-tab-content-item">
                                    <!-- Start - Review Comment -->
                                    <ul class="comment">
                                        <?php foreach ($reviews as $rev): ?>
                                        <li class="comment-list">
                                            <div class="comment-wrapper">
                                                <div class="comment-img">
                                                    <img src="/assets/images/user/avatar-svgrepo-com.svg" alt="">
                                                </div>
                                                <div class="comment-content">
                                                    <div class="comment-content-top">
                                                        <div class="comment-content-left">
                                                            <h6 class="comment-name"><?php echo $rev['name']; ?></h6>
                                                            <span class="date"><?php echo $rev['date']; ?></span>
                                                            <div class="product-review">
                                                                <span class="review-fill"><i class="fa fa-star"></i></span>
                                                                <span class="review-empty"><i class="fa fa-star"></i></span>
                                                                <span class="review-empty"><i class="fa fa-star"></i></span>
                                                                <span class="review-empty"><i class="fa fa-star"></i></span>
                                                                <span class="review-empty"><i class="fa fa-star"></i></span>
                                                            </div>
                                                        </div>
                                                        <div class="comment-content-right">
                                                            <a href="#"><i class="fa fa-reply"></i>Reply</a>
                                                        </div>
                                                    </div>

                                                    <div class="para-content">
                                                        <p><?php echo $rev['text']; ?></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </li>
                                        <?php endforeach ?>
                                    </ul>
                                    <div class="review-form">
                                        <div class="review-form-text-top">
                                            <h5>ДОБАВИТЬ ОТЗЫВ</h5>
                                        </div>

                                        <form action="/product/rev" method="post">
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <div class="default-form-box mb-20">
                                                        <label for="comment-name">Ваше имя <span>*</span></label>
                                                        <input id="comment-name" type="text" name="name" placeholder="Введите Ваше имя" required>
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="default-form-box mb-20">
                                                        <label for="comment-name">Ваша оценка <span>*</span></label>
                                                        <div class="product-grade">
                                                            <input id="product-grade" name="rating" min="1" max="5" value="5" type="number">
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-12">
                                                    <div class="default-form-box mb-20">
                                                        <label for="comment-review-text">Ваш отзыв <span>*</span></label>
                                                        <textarea id="comment-review-text" name="text" placeholder="Введите Ваш отзыв" required></textarea>
                                                    </div>
                                                </div>
                                                <input type="hidden" name="goods_id" class="input-field" value="<?php echo $product['id']; ?>">
                                                <div class="col-12">
                                                    <button class="form-submit-btn" type="submit">Submit</button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div> <!-- End Product Details Tab Content Singel -->
                        </div>
                    </div> <!-- End Product Details Tab Content -->

                </div>
            </div>
        </div>
    </div>
</div>