<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Галерея">
    <meta name="author" content="">
    <title>Магазин</title>
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
    <style>
        :root {
            --input-padding-x: .75rem;
            --input-padding-y: .75rem;
        }

        html,
        body {
            height: 100%;
        }

        /*body {*/
        /*    display: -ms-flexbox;*/
        /*    display: -webkit-box;*/
        /*    display: flex;*/
        /*    -ms-flex-align: center;*/
        /*    -ms-flex-pack: center;*/
        /*    -webkit-box-align: center;*/
        /*    align-items: start;*/
        /*    -webkit-box-pack: center;*/
        /*    justify-content: center;*/
        /*    padding-top: 40px;*/
        /*    padding-bottom: 40px;*/
        /*    background-color: #ffffff;*/
        /*}*/

        body {
            margin: 0;
            font-family: var(--bs-body-font-family);
            font-size: var(--bs-body-font-size);
            font-weight: var(--bs-body-font-weight);
            line-height: var(--bs-body-line-height);
            color: var(--bs-body-color);
            text-align: var(--bs-body-text-align);
            background-color: var(--bs-body-bg);
            -webkit-text-size-adjust: 100%;
            -webkit-tap-highlight-color: transparent;
        }

        .form-signin {
            width: 100%;
            max-width: 420px;
            padding: 0 15px;
            margin: 0 auto;
        }

        .form-label-group {
            position: relative;
            margin-bottom: 1rem;
        }

        .form-label-group > input,
        .form-label-group > label {
            padding: var(--input-padding-y) var(--input-padding-x);
        }

        .form-label-group > label {
            position: absolute;
            top: 0;
            left: 0;
            display: block;
            width: 100%;
            margin-bottom: 0; /* Override default `<label>` margin */
            line-height: 1.5;
            color: #495057;
            border: 1px solid transparent;
            border-radius: .25rem;
            transition: all .1s ease-in-out;
        }

        .form-label-group input::-webkit-input-placeholder {
            color: transparent;
        }

        .form-label-group input:-ms-input-placeholder {
            color: transparent;
        }

        .form-label-group input::-ms-input-placeholder {
            color: transparent;
        }

        .form-label-group input::-moz-placeholder {
            color: transparent;
        }

        .form-label-group input::placeholder {
            color: transparent;
        }

        .form-label-group input:not(:placeholder-shown) {
            padding-top: calc(var(--input-padding-y) + var(--input-padding-y) * (2 / 3));
            padding-bottom: calc(var(--input-padding-y) / 3);
        }

        .form-label-group input:not(:placeholder-shown) ~ label {
            padding-top: calc(var(--input-padding-y) / 3);
            padding-bottom: calc(var(--input-padding-y) / 3);
            font-size: 12px;
            color: #777;
        }

        .bd-example {
            padding: 1.3rem;
            margin-right: 0;
            margin-left: 0;
            margin-bottom: .8rem;
            border-radius: .25rem;
        }

        .bd-example {
            position: relative;
            border: 1px solid #dee2e6;
        }

        .main {
            max-width: 1800px;
            margin: 0 auto;
            display: flex;
            flex-direction: column;
        }

        /*.btn {*/
        /*    margin-top: 15px;*/
        /*}*/

        .form-text {
            color: #e15151;
        }

    </style>
    <!-- CSS
============================================ -->

    <link rel="stylesheet" href="../templates/layouts/ass/css/bootstrap.min.css" />
    <link rel="stylesheet" href="../templates/layouts/ass/css/font-awesome.min.css" />
    <link rel="stylesheet" href="../templates/layouts/ass/css/Pe-icon-7-stroke.css" />
    <link rel="stylesheet" href="../templates/layouts/ass/css/animate.min.css">
    <link rel="stylesheet" href="../templates/layouts/ass/css/swiper-bundle.min.css">
    <link rel="stylesheet" href="../templates/layouts/ass/css/nice-select.css">
    <link rel="stylesheet" href="../templates/layouts/ass/css/magnific-popup.min.css" />
    <link rel="stylesheet" href="../templates/layouts/ass/css/ion.rangeSlider.min.css" />

    <!-- Style CSS -->
    <link rel="stylesheet" href="../templates/layouts/ass/css/style.css">
</head>

<body>
    <div class="main">
        <header>
        <div class="px-3 py-2 bg-dark text-white">
            <div class="container">
                <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                    <a href="/" class="d-flex align-items-center my-2 my-lg-0 me-lg-auto text-white text-decoration-none">
                        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
                    </a>

                    <ul class="nav col-12 col-lg-auto my-2 justify-content-center my-md-0 text-small">
                        <li>
                            <a href="#" class="nav-link text-white">
                                <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#home"/></svg>
                                Home
                            </a>
                        </li>
                        <li>
                            <a href="#" class="nav-link text-white">
                                <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#speedometer2"/></svg>
                                Dashboard
                            </a>
                        </li>
                        <li>
                            <a href="#" class="nav-link text-white">
                                <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#table"/></svg>
                                Orders
                            </a>
                        </li>
                        <li>
                            <a href="/" class="nav-link text-secondary">
                                <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#grid"/></svg>
                                Products
                            </a>
                        </li>
                        <li>
                            <a href="#" class="nav-link text-white">
                                <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#people-circle"/></svg>
                                Customers
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="px-3 py-2 border-bottom mb-3">
            <div class="container d-flex flex-wrap justify-content-center">
                <form class="col-12 col-lg-auto mb-2 mb-lg-0 me-lg-auto"></form>

                <div class="text-end">
                    <button type="button" class="btn btn-light text-dark me-2">Login</button>
                    <button type="button" class="btn btn-primary">Sign-up</button>
                </div>
            </div>
        </div>
    </header>
        <div class="container">
            <?php echo $content; ?>
        </div>
        <footer class="py-3 my-4">
            <ul class="nav justify-content-center border-bottom pb-3 mb-3">
                <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
            </ul>
            <p class="text-center text-muted">© 2021 Company, Inc</p>
        </footer>
    </div>

<!--    <div class="modal fade" id="exampleModalToggle" aria-hidden="true" aria-labelledby="exampleModalToggleLabel" tabindex="-1">-->
<!--        <div class="modal-dialog modal-dialog-centered">-->
<!--            <div class="modal-content">-->
<!--                <div class="modal-header">-->
<!--                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>-->
<!--                </div>-->
<!--                <div class="modal-body">-->
<!--                   <img alt="" src="#" style="max-width: 100%; height: auto;">-->
<!--                </div>-->
<!--                <div class="modal-footer">-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->




<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
        crossorigin="anonymous"></script>


    <script src="../templates/layouts/ass/js/vendor/bootstrap.bundle.min.js"></script>
    <script src="../templates/layouts/ass/js/vendor/jquery-3.6.0.min.js"></script>
    <script src="../templates/layouts/ass/js/vendor/jquery-migrate-3.3.2.min.js"></script>
    <script src="../templates/layouts/ass/js/vendor/jquery.waypoints.js"></script>
    <script src="../templates/layouts/ass/js/vendor/modernizr-3.11.2.min.js"></script>
    <script src="../templates/layouts/ass/js/plugins/wow.min.js"></script>
    <script src="../templates/layouts/ass/js/plugins/swiper-bundle.min.js"></script>
    <script src="../templates/layouts/ass/js/plugins/jquery.nice-select.js"></script>
    <script src="../templates/layouts/ass/js/plugins/parallax.min.js"></script>
    <script src="../templates/layouts/ass/js/plugins/jquery.magnific-popup.min.js"></script>
    <script src="../templates/layouts/ass/js/plugins/tippy.min.js"></script>
    <script src="../templates/layouts/ass/js/plugins/ion.rangeSlider.min.js"></script>
    <script src="../templates/layouts/ass/js/plugins/mailchimp-ajax.js"></script>
    <script src="../templates/layouts/ass/js/plugins/jquery.counterup.js"></script>

    <!--Main JS (Common Activation Codes)-->
    <script src="../templates/layouts/ass/js/main.js"></script>
<!--<script>-->
<!--    var myModal = new bootstrap.Modal(document.getElementById('exampleModalToggle'), {-->
<!--        keyboard: false-->
<!--    });-->
<!--    function basename(path, suffix){-->
<!--        let p = path.split( /[\/\\]/ ), name = p[p.length-1];-->
<!--        return ('string'!=typeof suffix) ? name :-->
<!--        name.replace(new RegExp(suffix.replace('.', '\\.')+'$'),'');-->
<!--    }-->
<!---->
<!--    $('.card-img-top').on('click', function (e) {-->
<!--        let img = $(this);-->
<!--        let src = basename(img[0].src);-->
<!--        $('#exampleModalToggle img').attr('src', `photo/big/${src}`);-->
<!--        myModal.show();-->
<!--    });-->
<!---->
<!--    $( document ).ready(function(){-->
<!--        $('.img-delete').click(function(){-->
<!--            let id = $(this).data('id');-->
<!---->
<!--            $.ajax({-->
<!--                method: "POST",-->
<!--                url: "index.php",-->
<!--                data: {-->
<!--                    idImg: id-->
<!--                },-->
<!--                success: function(result){-->
<!--                    location.reload();-->
<!--                }-->
<!--            })-->
<!--        });-->
<!--    });-->
<!---->
<!--</script>-->
</body>
</html>