<div class="single-product-area section-space-top-100">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="single-product-img">
                    <div class="swiper-container single-product-slider">
                        <div class="swiper-wrapper">
                            <?php $collect = explode(',', $title_img); ?>
                            <?php foreach ($collect as $img): ?>
                            <div class="swiper-slide">
                                <a href="../templates/layouts/ass/images/product/large-size/1-1-570x633.jpg" class="single-img gallery-popup">
                                    <img class="img-full" src="../photo/big/<?php echo $img ?>" alt="Product Image">
                                </a>
                            </div>
                            <?php endforeach ?>

                        </div>
                    </div>
                    <div class="thumbs-arrow-holder">
                        <div class="swiper-container single-product-thumbs">
                            <div class="swiper-wrapper">
                                <?php $collect = explode(',', $title_img); ?>
                                <?php foreach ($collect as $img): ?>
                                    <a href="#" class="swiper-slide">
                                        <img class="img-full" src="../photo/big/<?php echo $img ?>" alt="Product Thumnail">
                                    </a>
                                <?php endforeach ?>
                            </div>
                            <!-- Add Arrows -->
                            <div class=" thumbs-button-wrap d-none d-md-block">
                                <div class="thumbs-button-prev">
                                    <i class="pe-7s-angle-left"></i>
                                </div>
                                <div class="thumbs-button-next">
                                    <i class="pe-7s-angle-right"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 pt-5 pt-lg-0">
                <div class="single-product-content">
                    <h2 class="title"><?php echo $title_good ?></h2>
                    <div class="price-box">
                        <span class="new-price"><?php echo $price ?> руб.</span>
                    </div>
                    <div class="rating-box-wrap">
                        <div class="rating-box">
                            <ul>
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                            </ul>
                        </div>
                        <div class="review-status">
                            <a href="#">( 1 Review )</a>
                        </div>
                    </div>
                    <div class="selector-wrap color-option">
                        <span class="selector-title border-bottom-0">Color</span>
                        <select class="nice-select wide border-bottom-0 rounded-0">
                            <option value="default">Black & White</option>
                            <option value="blue">Blue</option>
                            <option value="green">Green</option>
                            <option value="red">Red</option>
                        </select>
                    </div>
                    <div class="selector-wrap size-option">
                        <span class="selector-title">Size</span>
                        <select class="nice-select wide rounded-0">
                            <option value="medium">Medium Size & Poot</option>
                            <option value="large">Large Size With Poot</option>
                            <option value="small">Small Size With Poot</option>
                        </select>
                    </div>
                    <p class="short-desc"><?php echo $description ?></p>
                    <ul class="quantity-with-btn">
                        <li class="quantity">
                            <div class="cart-plus-minus">
                                <input class="cart-plus-minus-box" value="1" type="text">
                            </div>
                        </li>
                        <li class="add-to-cart">
                            <a class="btn btn-custom-size lg-size btn-pronia-primary" href="cart.html">Add to
                                cart</a>
                        </li>
                        <li class="wishlist-btn-wrap">
                            <a class="custom-circle-btn" href="wishlist.html">
                                <i class="pe-7s-like"></i>
                            </a>
                        </li>
                        <li class="compare-btn-wrap">
                            <a class="custom-circle-btn" href="compare.html">
                                <i class="pe-7s-refresh-2"></i>
                            </a>
                        </li>
                    </ul>
                    <ul class="service-item-wrap">
                        <li class="service-item">
                            <div class="service-img">
                                <img src="../templates/layouts/ass/images/shipping/icon/car.png" alt="Shipping Icon">
                            </div>
                            <div class="service-content">
                                <span class="title">Free <br> Shipping</span>
                            </div>
                        </li>
                        <li class="service-item">
                            <div class="service-img">
                                <img src="../templates/layouts/ass/images/shipping/icon/card.png" alt="Shipping Icon">
                            </div>
                            <div class="service-content">
                                <span class="title">Safe <br> Payment</span>
                            </div>
                        </li>
                        <li class="service-item">
                            <div class="service-img">
                                <img src="../templates/layouts/ass/images/shipping/icon/service.png" alt="Shipping Icon">
                            </div>
                            <div class="service-content">
                                <span class="title">Safe <br> Payment</span>
                            </div>
                        </li>
                    </ul>
                    <div class="product-category">
                        <span class="title">SKU:</span>
                        <ul>
                            <li>
                                <a href="#">Ch-256xl</a>
                            </li>
                        </ul>
                    </div>
                    <div class="product-category">
                        <span class="title">Categories :</span>
                        <ul>
                            <li>
                                <a href="#">Office,</a>
                            </li>
                            <li>
                                <a href="#">Home</a>
                            </li>
                        </ul>
                    </div>
                    <div class="product-category product-tags">
                        <span class="title">Tags :</span>
                        <ul>
                            <li>
                                <a href="#">Furniture</a>
                            </li>
                        </ul>
                    </div>
                    <div class="product-category social-link align-items-center pb-0">
                        <span class="title pe-3">Share:</span>
                        <ul>
                            <li>
                                <a href="#" data-tippy="Pinterest" data-tippy-inertia="true" data-tippy-animation="shift-away" data-tippy-delay="50" data-tippy-arrow="true" data-tippy-theme="sharpborder">
                                    <i class="fa fa-pinterest-p"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#" data-tippy="Twitter" data-tippy-inertia="true" data-tippy-animation="shift-away" data-tippy-delay="50" data-tippy-arrow="true" data-tippy-theme="sharpborder">
                                    <i class="fa fa-twitter"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#" data-tippy="Tumblr" data-tippy-inertia="true" data-tippy-animation="shift-away" data-tippy-delay="50" data-tippy-arrow="true" data-tippy-theme="sharpborder">
                                    <i class="fa fa-tumblr"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#" data-tippy="Dribbble" data-tippy-inertia="true" data-tippy-animation="shift-away" data-tippy-delay="50" data-tippy-arrow="true" data-tippy-theme="sharpborder">
                                    <i class="fa fa-dribbble"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
