<div class="form-signin">
    <div class="text-center mb-4">
        <h1 class="h3 mb-3 font-weight-normal">Каталог товаров</h1>
    </div>
</div>
<div class="row">
    <?php if (!empty($collect)): ?>
        <?php foreach ($collect as $product): ?>
            <div class="col-sm-3">
                <div class="card" style="width: 100%; margin-top: 15px; min-width: 150px;">
                    <img  src="photo/small/<?php echo $product['title_img'] ?>" class="card-img-top" alt="img">
                    <div class="card-body">
                        <h5 class="card-title"><?php echo $product['title_good'] ?></h5>
                        <p class="card-text"><?php echo $product['description'] ?>.</p>
                        <a href="/product/?id=<?php echo $product['id'] ?>"><button type="button" class="btn btn-outline-primary">Подробнее</button></a>
                    </div>
                    <div class="card-footer text-muted">
                        осталось на складе: <?php echo $product['quantity'] ?>
                    </div>
                </div>
            </div>
        <?php endforeach ?>
    <?php endif ?>
</div>
<br>
